version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
  monolith:
    build:
      context: .
      dockerfile: dev.dockerfile
    working_dir: /asiap
    ports:
      - "3001:3001"
    volumes:
      - .:/asiap
    depends_on:
      - rabbitmq
